version: '3.8'

services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    ports:
      - '5432:5432'

  clickhouse:
    image: clickhouse/clickhouse-server:24.12 
    restart: always
    ports: 
      - '9000:9000'
      - '8123:8123'

  minio:
    image: minio/minio:latest
    command: ['server', '/data', '--address', ':9001', '--console-address', ':9002']    
    ports:
      - '9001:9001'
      - '9002:9002' 
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9001 minio minio123;
      /usr/bin/mc mb local/agp-results;
      exit 0;
      "

  agp:  
    build: ./
    restart: always
    command: standalone --migrate
    ports:
      - '8888:8888'
    environment:
      - LOG_LEVEL=0
      - OBJSTR__S3__REGION=us-east-1
      - OBJSTR__S3__ACCESS_KEY_ID=minio
      - OBJSTR__S3__SECRET_ACCESS_KEY=minio123
      - OBJSTR__S3__DISABLE_SSL=true
      - OBJSTR__S3__FORCE_PATH_STYLE=true
      - OBJSTR__S3__ENDPOINT=http://minio:9001
      - AGP__DSN=postgres://postgres:postgres@postgres:5432/postgres
      - AGP__RESULT_STORAGE_PREFIX=s3://agp-results
      - AGP__RESULT_STORAGE_COMPRESSION=GZIP 
      - AGP__WORKER__BACKENDS__0__DSN=clickhouse://clickhouse:9000/default
      - AGP__SERVER__API__ASYNC__ENABLE=true 
      - AGP__SERVER__API__SYNC__ENABLE=true
      - AGP__SERVER__API__SYNC__BACKENDS__0__DSN=clickhouse://clickhouse:9000/default
      - AGP__SERVER__SECRET=secret 



      