//go:build go1.22

// Package async provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package async

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/agnosticeng/agp/internal/api/v1"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	SecretScopes = "Secret.Scopes"
)

// Defines values for ExecutionStatus.
const (
	CANCELED  ExecutionStatus = "CANCELED"
	FAILED    ExecutionStatus = "FAILED"
	PENDING   ExecutionStatus = "PENDING"
	RUNNING   ExecutionStatus = "RUNNING"
	SUCCEEDED ExecutionStatus = "SUCCEEDED"
)

// Defines values for SortBy.
const (
	COMPLETEDAT SortBy = "COMPLETED_AT"
	CREATEDAT   SortBy = "CREATED_AT"
)

// Execution defines model for Execution.
type Execution struct {
	CompletedAt *time.Time             `json:"completed_at,omitempty"`
	CreatedAt   time.Time              `json:"created_at"`
	Error       *string                `json:"error,omitempty"`
	Id          int64                  `json:"id"`
	PickedAt    *time.Time             `json:"picked_at,omitempty"`
	Progress    *externalRef0.Progress `json:"progress,omitempty"`
	Query       string                 `json:"query"`
	QueryHash   string                 `json:"query_hash"`
	QueryId     string                 `json:"query_id"`
	Result      *ResultMetadata        `json:"result,omitempty"`
	Status      ExecutionStatus        `json:"status"`
}

// ExecutionStatus defines model for ExecutionStatus.
type ExecutionStatus string

// Query defines model for Query.
type Query struct {
	Secrets *[]Secret `json:"secrets,omitempty"`
	Sql     string    `json:"sql"`
}

// ResultMetadata defines model for ResultMetadata.
type ResultMetadata struct {
	Duration *int64                 `json:"duration,omitempty"`
	Meta     *[]externalRef0.Column `json:"meta,omitempty"`
	Rows     *int64                 `json:"rows,omitempty"`
}

// SearchQuery defines model for SearchQuery.
type SearchQuery = []SearchQueryItem

// SearchQueryItem defines model for SearchQueryItem.
type SearchQueryItem struct {
	Limit     *int32             `json:"limit,omitempty"`
	QueryHash *string            `json:"query_hash,omitempty"`
	QueryId   string             `json:"query_id"`
	SortBy    *SortBy            `json:"sort_by,omitempty"`
	Statuses  *[]ExecutionStatus `json:"statuses,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult = [][]Execution

// Secret defines model for Secret.
type Secret struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// SortBy defines model for SortBy.
type SortBy string

// ExecutionId defines model for ExecutionId.
type ExecutionId = int64

// Expiration defines model for Expiration.
type Expiration = int64

// QueryId defines model for QueryId.
type QueryId = string

// Signature defines model for Signature.
type Signature = string

// PostExecutionsTextBody defines parameters for PostExecutions.
type PostExecutionsTextBody = string

// PostExecutionsParams defines parameters for PostExecutions.
type PostExecutionsParams struct {
	Tier     *externalRef0.Tier     `form:"tier,omitempty" json:"tier,omitempty"`
	QuotaKey *externalRef0.QuotaKey `form:"quota-key,omitempty" json:"quota-key,omitempty"`
	QueryId  *QueryId               `form:"query-id,omitempty" json:"query-id,omitempty"`
}

// GetExecutionsExecutionIdParams defines parameters for GetExecutionsExecutionId.
type GetExecutionsExecutionIdParams struct {
	Tier     *externalRef0.Tier     `form:"tier,omitempty" json:"tier,omitempty"`
	QuotaKey *externalRef0.QuotaKey `form:"quota-key,omitempty" json:"quota-key,omitempty"`
}

// GetExecutionsExecutionIdResultParams defines parameters for GetExecutionsExecutionIdResult.
type GetExecutionsExecutionIdResultParams struct {
	Tier       *externalRef0.Tier     `form:"tier,omitempty" json:"tier,omitempty"`
	QuotaKey   *externalRef0.QuotaKey `form:"quota-key,omitempty" json:"quota-key,omitempty"`
	Signature  Signature              `form:"signature" json:"signature"`
	Expiration Expiration             `form:"expiration" json:"expiration"`
}

// PostSearchParams defines parameters for PostSearch.
type PostSearchParams struct {
	Tier     *externalRef0.Tier     `form:"tier,omitempty" json:"tier,omitempty"`
	QuotaKey *externalRef0.QuotaKey `form:"quota-key,omitempty" json:"quota-key,omitempty"`
}

// PostExecutionsJSONRequestBody defines body for PostExecutions for application/json ContentType.
type PostExecutionsJSONRequestBody = Query

// PostExecutionsTextRequestBody defines body for PostExecutions for text/plain ContentType.
type PostExecutionsTextRequestBody = PostExecutionsTextBody

// PostSearchJSONRequestBody defines body for PostSearch for application/json ContentType.
type PostSearchJSONRequestBody = SearchQuery

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /executions)
	PostExecutions(w http.ResponseWriter, r *http.Request, params PostExecutionsParams)

	// (GET /executions/{execution_id})
	GetExecutionsExecutionId(w http.ResponseWriter, r *http.Request, executionId ExecutionId, params GetExecutionsExecutionIdParams)

	// (GET /executions/{execution_id}/result)
	GetExecutionsExecutionIdResult(w http.ResponseWriter, r *http.Request, executionId ExecutionId, params GetExecutionsExecutionIdResultParams)

	// (POST /search)
	PostSearch(w http.ResponseWriter, r *http.Request, params PostSearchParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostExecutions operation middleware
func (siw *ServerInterfaceWrapper) PostExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostExecutionsParams

	// ------------- Optional query parameter "tier" -------------

	err = runtime.BindQueryParameter("form", true, false, "tier", r.URL.Query(), &params.Tier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tier", Err: err})
		return
	}

	// ------------- Optional query parameter "quota-key" -------------

	err = runtime.BindQueryParameter("form", true, false, "quota-key", r.URL.Query(), &params.QuotaKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quota-key", Err: err})
		return
	}

	// ------------- Optional query parameter "query-id" -------------

	err = runtime.BindQueryParameter("form", true, false, "query-id", r.URL.Query(), &params.QueryId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutionsExecutionId operation middleware
func (siw *ServerInterfaceWrapper) GetExecutionsExecutionId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "execution_id" -------------
	var executionId ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "execution_id", r.PathValue("execution_id"), &executionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "execution_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExecutionsExecutionIdParams

	// ------------- Optional query parameter "tier" -------------

	err = runtime.BindQueryParameter("form", true, false, "tier", r.URL.Query(), &params.Tier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tier", Err: err})
		return
	}

	// ------------- Optional query parameter "quota-key" -------------

	err = runtime.BindQueryParameter("form", true, false, "quota-key", r.URL.Query(), &params.QuotaKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quota-key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutionsExecutionId(w, r, executionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutionsExecutionIdResult operation middleware
func (siw *ServerInterfaceWrapper) GetExecutionsExecutionIdResult(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "execution_id" -------------
	var executionId ExecutionId

	err = runtime.BindStyledParameterWithOptions("simple", "execution_id", r.PathValue("execution_id"), &executionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "execution_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExecutionsExecutionIdResultParams

	// ------------- Optional query parameter "tier" -------------

	err = runtime.BindQueryParameter("form", true, false, "tier", r.URL.Query(), &params.Tier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tier", Err: err})
		return
	}

	// ------------- Optional query parameter "quota-key" -------------

	err = runtime.BindQueryParameter("form", true, false, "quota-key", r.URL.Query(), &params.QuotaKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quota-key", Err: err})
		return
	}

	// ------------- Required query parameter "signature" -------------

	if paramValue := r.URL.Query().Get("signature"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "signature"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "signature", r.URL.Query(), &params.Signature)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "signature", Err: err})
		return
	}

	// ------------- Required query parameter "expiration" -------------

	if paramValue := r.URL.Query().Get("expiration"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "expiration"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "expiration", r.URL.Query(), &params.Expiration)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "expiration", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutionsExecutionIdResult(w, r, executionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSearch operation middleware
func (siw *ServerInterfaceWrapper) PostSearch(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SecretScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostSearchParams

	// ------------- Optional query parameter "tier" -------------

	err = runtime.BindQueryParameter("form", true, false, "tier", r.URL.Query(), &params.Tier)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tier", Err: err})
		return
	}

	// ------------- Optional query parameter "quota-key" -------------

	err = runtime.BindQueryParameter("form", true, false, "quota-key", r.URL.Query(), &params.QuotaKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quota-key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/executions", wrapper.PostExecutions)
	m.HandleFunc("GET "+options.BaseURL+"/executions/{execution_id}", wrapper.GetExecutionsExecutionId)
	m.HandleFunc("GET "+options.BaseURL+"/executions/{execution_id}/result", wrapper.GetExecutionsExecutionIdResult)
	m.HandleFunc("POST "+options.BaseURL+"/search", wrapper.PostSearch)

	return m
}

type PostExecutionsRequestObject struct {
	Params   PostExecutionsParams
	JSONBody *PostExecutionsJSONRequestBody
	TextBody *PostExecutionsTextRequestBody
}

type PostExecutionsResponseObject interface {
	VisitPostExecutionsResponse(w http.ResponseWriter) error
}

type PostExecutions201JSONResponse Execution

func (response PostExecutions201JSONResponse) VisitPostExecutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionsExecutionIdRequestObject struct {
	ExecutionId ExecutionId `json:"execution_id"`
	Params      GetExecutionsExecutionIdParams
}

type GetExecutionsExecutionIdResponseObject interface {
	VisitGetExecutionsExecutionIdResponse(w http.ResponseWriter) error
}

type GetExecutionsExecutionId200JSONResponse Execution

func (response GetExecutionsExecutionId200JSONResponse) VisitGetExecutionsExecutionIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionsExecutionId404Response struct {
}

func (response GetExecutionsExecutionId404Response) VisitGetExecutionsExecutionIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetExecutionsExecutionIdResultRequestObject struct {
	ExecutionId ExecutionId `json:"execution_id"`
	Params      GetExecutionsExecutionIdResultParams
}

type GetExecutionsExecutionIdResultResponseObject interface {
	VisitGetExecutionsExecutionIdResultResponse(w http.ResponseWriter) error
}

type GetExecutionsExecutionIdResult200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetExecutionsExecutionIdResult200ApplicationoctetStreamResponse) VisitGetExecutionsExecutionIdResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetExecutionsExecutionIdResult404Response struct {
}

func (response GetExecutionsExecutionIdResult404Response) VisitGetExecutionsExecutionIdResultResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostSearchRequestObject struct {
	Params PostSearchParams
	Body   *PostSearchJSONRequestBody
}

type PostSearchResponseObject interface {
	VisitPostSearchResponse(w http.ResponseWriter) error
}

type PostSearch200JSONResponse SearchResult

func (response PostSearch200JSONResponse) VisitPostSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /executions)
	PostExecutions(ctx context.Context, request PostExecutionsRequestObject) (PostExecutionsResponseObject, error)

	// (GET /executions/{execution_id})
	GetExecutionsExecutionId(ctx context.Context, request GetExecutionsExecutionIdRequestObject) (GetExecutionsExecutionIdResponseObject, error)

	// (GET /executions/{execution_id}/result)
	GetExecutionsExecutionIdResult(ctx context.Context, request GetExecutionsExecutionIdResultRequestObject) (GetExecutionsExecutionIdResultResponseObject, error)

	// (POST /search)
	PostSearch(ctx context.Context, request PostSearchRequestObject) (PostSearchResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostExecutions operation middleware
func (sh *strictHandler) PostExecutions(w http.ResponseWriter, r *http.Request, params PostExecutionsParams) {
	var request PostExecutionsRequestObject

	request.Params = params
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/json") {

		var body PostExecutionsJSONRequestBody
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
		request.JSONBody = &body
	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "text/plain") {
		data, err := io.ReadAll(r.Body)
		if err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
			return
		}
		body := PostExecutionsTextRequestBody(data)
		request.TextBody = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostExecutions(ctx, request.(PostExecutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExecutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostExecutionsResponseObject); ok {
		if err := validResponse.VisitPostExecutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecutionsExecutionId operation middleware
func (sh *strictHandler) GetExecutionsExecutionId(w http.ResponseWriter, r *http.Request, executionId ExecutionId, params GetExecutionsExecutionIdParams) {
	var request GetExecutionsExecutionIdRequestObject

	request.ExecutionId = executionId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecutionsExecutionId(ctx, request.(GetExecutionsExecutionIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecutionsExecutionId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionsExecutionIdResponseObject); ok {
		if err := validResponse.VisitGetExecutionsExecutionIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecutionsExecutionIdResult operation middleware
func (sh *strictHandler) GetExecutionsExecutionIdResult(w http.ResponseWriter, r *http.Request, executionId ExecutionId, params GetExecutionsExecutionIdResultParams) {
	var request GetExecutionsExecutionIdResultRequestObject

	request.ExecutionId = executionId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecutionsExecutionIdResult(ctx, request.(GetExecutionsExecutionIdResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecutionsExecutionIdResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionsExecutionIdResultResponseObject); ok {
		if err := validResponse.VisitGetExecutionsExecutionIdResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSearch operation middleware
func (sh *strictHandler) PostSearch(w http.ResponseWriter, r *http.Request, params PostSearchParams) {
	var request PostSearchRequestObject

	request.Params = params

	var body PostSearchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSearch(ctx, request.(PostSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSearch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSearchResponseObject); ok {
		if err := validResponse.VisitPostSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYXU/jOBf+K+i872UgZUB70btSsqNqZ7qFMleoqkxyaD0kcbBPWCKU/76yneabNhUz",
	"K+aqGR+fj+c557HNG/giSkSMMSkYv0HCJIuQUJov7xX9lLiIZ4H+5DGMIWG0BQdiFiGMAXcWax6AAxKf",
	"Uy4xgDHJFB1Q/hYjpvc+ChkxgjHwmP64BAcoS9B+4gYl5LkD3mvCJdPeymjPKcqsHq60+GiwG+25Vlcr",
	"kvk8NUVVfgs3iiSPN8bLkm9iRqnE9/yo0mBfwl3HvogiEa9vUkHsL8zeT1MQO33CDAa5u+Mo33NFem2f",
	"l3y32OwN0zZSJCiJo1nSLRUiYbDWJNToCBjhKfEIK0p23h3wJbJj96CUQvbk6gAPBjWCAwn3n46Mmkix",
	"kahMrf+X+Ahj+J9bzZFboOQWoC925rlTYN6XsFlZb5na7lm2VXUWJao0pEPp3Bqr70gsYMT0PkWM0oNl",
	"lEwvrXme11v5HsyQlPk1Kmmw6pQdV8RdldiKh5/oExgNaAYbvwHGaaTjLLz59Wz+FRy4/TGf21/TyXzq",
	"ffOuwYE/JzP7Y/ljOvW8a++6FqDC6mbHQLNnFfoSrQZywuggKEtjrx0WEZiULDOgPof9M1jHTBv1ld/i",
	"qJNmkFYCOaC5I7ROBpVUtOtUhGkU91UmxT9qqLx2Klsik/62RH8gyOWeGWHUl1PbpINYyCNuRiPAR2am",
	"5MJpVHDxpRe6j8yjEpLWD9nB8oSkq6waxILiXZ73tU4u23vlDIOuM7Rt6FoNWdazepe721JlygyOS6WP",
	"vy6fZq46ND5hv2y+sDDFw/NmT0hr3FuhpaKmNtNbb3LnXa8nd1pm/v6++OYVn32q0pydTvb2iO1J3/7H",
	"oezN9sK4L/v2QdOJ/5ARqoGagSFLFPYfnxGPeaTxGfXtHKwPDpAgFq4/JChF0VVXtpSStaSPBQHXXcjC",
	"Rd2wz3W7KT+NjGqpQD+VnLKlDmdLrWbG5KA3XDHF/crlliixNzgePwrTcJxCvTLZxEIR908WUrxmJxOV",
	"xf7JZDHT04JSmaMGzs9GZyOdukgwZgmHMVycjc60cOrngEnCLZ8Ctv+EMhlppNnuCQELocir7JzGe+O+",
	"H9fKxK3fYnNnqHl5hx6wZfcqyFd2AlHRlQgye6uNCWNTFEuSkPumLPensqdxdW/e1xz2/DPM4iu5Sch4",
	"a3fPrbv5brD3vUTExXnxZXT+y9KrSbX959R5dd/qz71cO9tgD8tfsUZy/Q35+fiuZ2c5byA7+k3IOnA5",
	"utTicwBit7rZH4V0IYqfHO/D5tXzepDv8o8DR1IpfEI6VSSRRcMpbR5ATVornda45ytDszLXqP3qaK9a",
	"/zlzv0nu6pf+QVI2+sWha+RYguq0lAfn/UoDoFC+7OBOZQhjcF/OXaZPRMhX+b8BAAD//zQcNr4rEwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
