package: async
output: api.gen.go
generate:
  models: true
  std-http-server: true
  strict-server: true
  embedded-spec: true
import-mapping:
  ../common.yaml: github.com/agnosticeng/agp/internal/api/v1