openapi: 3.0.2

info:
  version: 1.0.0
  title: Agnostic Proxy Clickouse HTTP API

servers:
  - url: /v1

security:
  - {}
  - Secret: []

components:
  securitySchemes:
    Secret:
      type: http
      scheme: bearer

paths:
  /:
    post:
      parameters:
        - $ref: '../common.yaml#/components/parameters/Authorization'
        - $ref: '../common.yaml#/components/parameters/QuotaKey'
        - $ref: '../common.yaml#/components/parameters/Tier'
        - in: query
          name: default_format
          schema:
            type: string
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
          application/x-www-form-urlencoded: {}
      responses:
        "200":
          content:
            application/octet-stream: {}